en:
    languageName: ":gb:"
    languageAltTitle: English
    weight: 1
    title: "JG"
    taxonomies:
      cv: CV
      contact: Contact
      projects: Projects
    profileMode:
        enabled: true
        title: Javier Gutierrez
        imageUrl: "img/photo.png"
        imageTitle: Javier Gutierrez's photo
        # imageWidth: 120
        # imageHeight: 120
        # ğŸ“
        subtitle: "ğŸ—ºï¸ GIS Developer | ğŸ’¡ Product Owner | ğŸ¤ Team Lead"
        buttons:
            - name: CV
              url: cv
            - name: Projects
              url: projects
            - name: Contact
              url: contact
    menu:
        main:
            - name: CV
              url: cv
              weight: 1
            - name: Projects
              url: projects
              weight: 5
            - name: Contact
              url: contact
              weight: 10



# de:
#     languageName: ":de:"
#     languageAltTitle: Deutsch
#     weight: 2
#     title: ""
#     taxonomies:
#       cv: CV_de
#       contact: Contact_de
#       projects: Projects_de
#     profileMode:
#         enabled: true
#         title: Javier Gutierrez
#         imageUrl: "img/photo.png"
#         imageTitle: Javier Gutierrez's photo
#         # imageWidth: 120
#         # imageHeight: 120
#         # ğŸ“
#         subtitle: "ğŸ—ºï¸ GIS Entwickler | ğŸ’¡ Product Owner | ğŸ¤ Team Leiter"
#         buttons:
#             - name: CV_de
#               url: cv
#             - name: Contact_de
#               url: contact
#             - name: Projects_de
#               url: projects
#     # menu:
#     #     main:
#     #         - name: Archive
#     #           url: archives/
#     #           weight: 5
#     #         - name: FRTags
#     #           url: frtags
#     #           weight: 10
#     #         - name: FRCategories
#     #           url: frcategories
#     #           weight: 10
#     #         - name: FRSeries
#     #           url: frseries
#     #           weight: 10
#     #         - name: NullLink
#     #           url: "#"

